import { NextPage } from "next";
import Head from "next/head";

export const Header: NextPage = () => {
  return (
    <>
      <Head>
        <title>T3 Todo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}